// ============================================================
//  TRANSLATIONS - English & French
// ============================================================

const translations = {
    en: {
        "page_title": "welcome· Sucess Technology",
        "hero_badge": "🔥 New Arrival",
        "hero_title": "Next-Gen Smartphone",
        "hero_brand": "Brand X",
        "hero_price": "$999",
        "hero_original_price": "$1,299",
        "hero_discount": "-23%",
        "hero_desc": "Experience the future today.",
        "hero_btn": "Shop Now",
        "categories_tag": "Popular Categories",
        "categories_title": "Shop by Category",
        "categories_sub": "Explore our best selling departments",
        "view_all": "View All",
        "deals_title": "Deals du Jour",
        "deals_view_all": "Voir Plus →",
        "related_title": "You May Also Like",
        "footer_products": "Products",
        "footer_phone": "Phone",
        "footer_tablet": "Tablet",
        "footer_audio": "Audio",
        "footer_follow": "📱 Follow Us",
        "footer_about": "About",
        "footer_about_us": "About Us",
        "footer_locate": "Locate Us",
        "footer_terms": "Terms & Conditions",
        "footer_contact": "📞 Contact",
        "nav_products": "Products",
  "nav_categories": "Categories", 
  "nav_brands": "Brands",
  "nav_contact": "Contact",
  "notif_empty_title": "No notifications",
  "notif_empty_sub": "You're all caught up!",
  "notif_mark_all": "Mark all as read",
  "notif_unread_count": "{count} unread",
  "notif_clear_all": "Clear all notifications",
  "notif_just_now": "Just now",
   "nav_products": "Products",
  "nav_categories": "Categories",
  "nav_brands": "Brands",
  "nav_contact": "Contact",
  "view_all": "View All →",
  "loading": "Loading...",
  "search_placeholder": "Search...",
  "guest": "Guest",
  "my_orders": "My Orders",
  "settings": "Settings",
  "logout": "Logout",
  "about_us": "About Us",
  "terms": "Terms & Conditions",
  "locate_us": "Locate Us",
  "login": "Login",
  "register": "Register",
  "home": "Home",
  "for_you": "for you",
  "cart": "Cart",
  "wishlist": "Wishlist",
  "notifications_title": "Notifications",
  "welcome_back": "Welcome Back",
  "login_subtitle": "Login to your account",
  "email_address": "Email Address",
  "email_placeholder": "you@example.com",
  "email_error": "Please enter a valid email",
  "password": "Password",
  "password_placeholder": "Enter your password",
  "password_error": "Password is required",
  "remember_me": "Remember me",
  "no_account": "Don't have an account?",
  "create_account": "Create Account",
  "join_subtitle": "Join Success Technology",
  "full_name": "Full Name",
  "name_placeholder": "John Doe",
  "name_error": "Name is required",
  "password_help": "Password must be at least 6 characters",
  "phone_number": "Phone Number",
  "phone_placeholder": "6XX XXX XXX",
  "phone_help": "We'll use this to contact you about your orders",
  "phone_error": "Please enter a valid phone number",
  "delivery_address": "Delivery Address",
  "address_placeholder": "123 Main St, City, Country",
  "address_help": "Your default delivery address",
  "address_error": "Please enter your address",
  "country_region": "Country / Region",
  "select_country": "Select your country",
  "country_help": "Select your country for shipping and currency",
  "country_error": "Please select your country",
  "terms_agree": "I agree to the Terms of Service and Privacy Policy.",
  "terms_error": "You must agree to the terms to create an account",
  "have_account": "Already have an account?",
    "no_categories": "No categories available",
  "no_brands": "No brands available",
  "no_products": "No products available",
  "load_failed": "Failed to load products",
  "product_count": "{count} products",
  "product_price": "FCFA{price}",
   "searching": "Searching...",
  "no_results": "No products found for",
  "view_all_results": "View all results for",
  "search_unavailable": "Search unavailable. Please try again.",
  "type_to_search": "Type to search products...",
  "notif_redirect_checkout": " Redirecting to checkout...",
"notif_welcome_back": " Welcome back, {name}!",
"notif_login_failed": "❌ Login failed. Please try again.",
"notif_registration_success": " Account successfully created! Welcome {name}!",
"notif_registration_failed": "❌ Registration failed. Please try again.",
"notif_logout_success": "👋 Logout successful",
 "no_featured_title": "No featured products available",
  "no_featured_sub": "Check back soon for our latest deals!",
  "badge_deal": "🔥 Deal",
  "badge_new": "✨ New",
  "badge_hot": "⚡ Hot",
  "view_details": "View Details",
  "no_products_found": "No products found",
  "check_back_later": "Check back later for new arrivals",
  "badge_discount": "-{0}%",
  "badge_new": "✨ New",
  "badge_hot": "⚡ Hot",
  "view_details": "View Details",
  "loading_more": "Loading more products...",
  "load_more": "Load more products",
  "no_products_available": "No products available",
  "error_loading": "Error loading products",
  "please_try_again": "Please try again later",
  "retry": "Retry",
  "hot_products_title": "Hot Products",
  "view_all": "View All",
  "no_hot_products": "No hot products available",
  "discount_percent": "-{0}%",
  "view_details": "View Details",
   "wishlist_page_title": "Your Wishlist - Sucess Technology",
  "wishlist_title": "Your Wishlist",
  "items_count": "{0} items",
  "clear_all": "Clear All",
  "browse_products": "Browse Products",
  "badge_deal": "🔥 Deal",
  "badge_new": "✨ New",
  "badge_hot": "⚡ Hot",
  "remove": "Remove from wishlist",
  "view_details": "View Details",
  "empty_wishlist_title": "Your wishlist is empty",
  "empty_wishlist_sub": "Save your favorite items and come back to them anytime.",
  "start_exploring": "Start Exploring",
  "error_title": "Something went wrong",
  "error_sub": "We couldn't load your wishlist. Please try again later.",
  "retry": "Retry",
   "about_page_title": "About Us · Sucess Technology",
  "loading_info": "Loading company information...",
  "about_title": "About",
  "hero_description": "Your trusted partner for premium technology products and exceptional service. We're committed to bringing you the best in tech innovation.",
  "location_default": "Douala, Cameroon",
  "hours_default": "Mon - Fri: 7:00 AM - 8:00 PM",
  "stat_years": "3+",
  "stat_years_label": "Years of Excellence",
  "stat_products": "500+",
  "stat_products_label": "Products Available",
  "stat_customers": "1000+",
  "stat_customers_label": "Happy Customers",
  "shop_photo": "Shop Photo",
  "mission_title": "Our Mission",
  "mission_text": "To provide high-quality technology products and exceptional customer service that empowers individuals and businesses to achieve more.",
  "vision_title": "Our Vision",
  "vision_text": "To become the most trusted technology partner in Africa, connecting people with innovative solutions that enhance their lives.",
  "values_title": "Our Values",
  "values_text": "Integrity, innovation, and customer-centricity drive everything we do. We believe in building lasting relationships with our community.",
  "who_we_are": "Who We Are",
  "about_description": "Sucess Technology is a premier technology retailer dedicated to bringing the latest and most innovative products to our customers. With a passion for technology and a commitment to excellence, we curate a diverse selection of high-quality devices and accessories.",
  "about_description_2": "Our team of technology enthusiasts is here to help you find the perfect product for your needs. Whether you're a professional looking for the latest laptop, a student seeking a reliable tablet, or a tech enthusiast exploring new gadgets, we've got you covered.",
  "about_description_3": "We believe that technology should be accessible to everyone, which is why we offer competitive prices, flexible payment options, and exceptional customer support. Your satisfaction is our priority.",
  "get_in_touch": "Get in Touch",
  "shop_now": "Shop Now",
  "core_values": "Our Core Values",
  "value_trust": "Trust & Integrity",
  "value_innovation": "Innovation",
  "value_customer": "Customer First",
  "value_quality": "Quality Excellence",
  "value_community": "Community Focus",
  "value_africa": "African Innovation",
  "get_in_touch_title": "Get in Touch",
  "connect_social": "Connect with us on social media",
  "no_contact": "No contact information available",
  "no_social": "No social links available",
  "account_page_title": "Account Settings · Success Technology",
  "account_settings_title": "Account Settings",
  "signed_in_guest": "Signed in as Guest",
  "guest": "Guest",
  "not_logged_in": "Not logged in",
  "nav_profile": "Profile",
  "nav_orders": "My Orders",
  "nav_security": "Security",
  "nav_preferences": "Preferences",
  "nav_logout": "Logout",
  "quick_links": "Quick Links",
  "about_us": "About Us",
  "terms": "Terms & Conditions",
  "locate_us": "Locate Us",
  "profile_info": "Profile Information",
  "enable_editing": "Enable Editing",
  "full_name": "Full Name",
  "full_name_placeholder": "Your full name",
  "name_required": "Name is required",
  "email_address": "Email Address",
  "email_placeholder": "you@example.com",
  "email_cannot_change": "Email cannot be changed",
  "phone_number": "Phone Number",
  "phone_placeholder": "+1 234 567 890",
  "address": "Address",
  "address_placeholder": "123 Main St, City",
  "bio": "Bio",
  "bio_placeholder": "Tell us a little about yourself...",
  "save_changes": "Save Changes",
  "reset": "Reset",
  "my_orders": "My Orders",
  "loading_orders": "Loading your orders...",
  "security": "Security",
  "current_password": "Current Password",
  "current_password_placeholder": "Enter current password",
  "current_password_required": "Current password is required",
  "new_password": "New Password",
  "new_password_placeholder": "Enter new password (min 6 characters)",
  "password_min_length": "Password must be at least 6 characters",
  "confirm_password": "Confirm New Password",
  "confirm_password_placeholder": "Confirm new password",
  "passwords_mismatch": "Passwords do not match",
  "update_password": "Update Password",
  "danger_zone": "Danger Zone",
  "delete_account_warning": "Permanently delete your account and all associated data.",
  "delete_account": "Delete Account",
  "preferences_title": "Preferences",
  "email_notifications": "Email Notifications",
  "pref_order_updates": "Order updates and confirmations",
  "pref_promotions": "Promotional emails and offers",
  "pref_newsletter": "Newsletter and product updates",
  "privacy": "Privacy",
  "pref_profile_visibility": "Show profile information to other users",
  "pref_order_history": "Show order history",
  "save_preferences": "Save Preferences",
  "delete_account_modal_title": "Delete Account",
  "delete_account_modal_text": "Are you sure you want to delete your account? This action is permanent and cannot be undone. All your data, including orders and preferences, will be lost.",
  "cancel": "Cancel",
  "delete_account_confirm": "Delete Account",
  "no_orders_yet": "No orders yet",
  "start_shopping": "Start shopping to see your orders here.",
  "browse_products": "Browse Products",
  "order_number": "Order",
  "items": "items",
  "please_login": "Please Login",
  "login_to_view_orders": "Login to view your orders.",
  "failed_to_load": "Failed to load orders",
  "try_again_later": "Please try again later.",
  "retry": "Retry",
  "brand_page_title": "brand · Sucess Technology",
  "all_brands": "All Brands",
  "explore_collection": "Explore our collection",
  "load_more": "Load More",
  "no_products_found": "No products found for this brand.",
  "you_may_also_like": "🔄 You May Also Like",
  "loading_more_products": "Loading more products...",
  "footer_products": "Products",
  "footer_phone": "Phone",
  "footer_tablet": "Tablet",
  "footer_audio": "Audio",
  "footer_follow": "📱 Follow Us",
  "footer_about": "About",
  "about_us": "About Us",
  "press": "Press",
  "locate_us": "📍 Locate Us",
  "footer_contact": "📞 Contact",
  "copyright": "© 2024 Sucess Technology. All rights reserved.",
  "badge_hot": "HOT",
  "badge_new": "NEW",
  "badge_deal": "DEAL",
  "add_to_cart": "Add to Cart",
  "cart_empty": "Cart empty",
  "cart_page_title": "Your Cart - Success Technology",
  "your_cart": "Your Cart",
  "items_count": "{0} items",
  "items_count_zero": "0 items",
  "continue_shopping": "Continue Shopping",
  "loading_cart": "Loading your cart...",
  "order_summary": "Order Summary",
  "subtotal": "Subtotal",
  "shipping": "Shipping",
  "discount": "Discount",
  "total": "Total",
  "discount_code_placeholder": "Discount code",
  "apply": "Apply",
  "proceed_to_checkout": "Proceed to Checkout",
  "you_may_also_like": "You May Also Like to add these to your bag too",
  "footer_products": "Products",
  "footer_phone": "Phone",
  "footer_tablet": "Tablet",
  "footer_audio": "Audio",
  "footer_follow": "📱 Follow Us",
  "footer_about": "About",
  "locate_us": "📍 Locate Us",
  "footer_contact": "📞 Contact",
  "cart_empty_title": "Your cart is empty",
  "cart_empty_sub": "Looks like you haven't added any items to your cart yet.",
  "start_shopping": "Start Shopping",
  "items": "item",
  "deal": "DEAL",
  "decrease_quantity": "Decrease quantity",
  "increase_quantity": "Increase quantity",
  "remove_item": "Remove item",
  "remove": "Remove",
  "removed_from_cart": "Removed",
  "from_cart": "from cart",
  "free": "Free",
  "discount_applied": "10% discount applied!",
  "discount_applied_20": "20% discount applied!",
  "discount_removed": "Discount removed",
  "invalid_discount": "Invalid discount code",
  "please_login_to_checkout": "Please login to checkout",
   "category_page_title": "Category · Sucess Technology",
  "all_categories": "All Categories",
  "explore_collection": "Explore our collection",
  "explore_collection_full": "Explore our complete collection",
  "discover_products": "Discover our {0} products",
  "load_more": "Load More",
  "no_products_found": "No products found for this category.",
  "you_may_also_like": "🔄 You May Also Like",
  "loading_more_products": "Loading more products...",
  "footer_products": "Products",
  "footer_phone": "Phone",
  "footer_tablet": "Tablet",
  "footer_audio": "Audio",
  "footer_follow": "📱 Follow Us",
  "footer_about": "About",
  "about_us": "About Us",
  "press": "Press",
  "locate_us": "📍 Locate Us",
  "footer_contact": "📞 Contact",
  "copyright": "© 2024 Sucess Technology. All rights reserved.",
  "badge_hot": "HOT",
  "badge_new": "NEW",
  "badge_deal": "DEAL",
  "add_to_cart": "Add to Cart",
  "cart_empty": "Cart empty",
  "product_not_found": "Product not found",
  "added_to_cart": "added to cart!",
  "cart_cleared": "Cart cleared",
  "error_loading_products": "Error loading products",
  "category_phone": "Phone",
  "category_tablet": "Tablet",
  "category_audio": "Audio",
  "category_laptop": "Laptop",
  "category_accessories": "Accessories",
  "category_watch": "Watch",
  "category_camera": "Camera",
  "category_gaming": "Gaming",
  "category_tv": "TV",
  "category_headphones": "Headphones",
  "category_speaker": "Speaker",
  "category_charger": "Charger",
  "category_case": "Case",
  "category_screen": "Screen",
  "category_uncategorized": "Uncategorized",
   "checkout_page_title": "Checkout · Sucess Technology",
  "checkout_title": "Checkout",
  "back_to_cart": "Back to Cart",
  "order_placed_title": "Order Placed! 🎉",
  "order_placed_sub": "Thank you for your order. We'll confirm it shortly.",
  "confirmation_sent": "A confirmation has been sent to your email.",
  "continue_shopping": "Continue Shopping",
  "view_orders": "View Orders",
  "contact_whatsapp": "Contact Seller on WhatsApp",
  "shipping_info": "Shipping Information",
  "full_name": "Full Name",
  "full_name_placeholder": "John Doe",
  "name_error": "Please enter your full name",
  "email_address": "Email Address",
  "email_placeholder": "you@example.com",
  "email_error": "Please enter a valid email",
  "phone_number": "Phone Number",
  "phone_placeholder": "+237 6XX XXX XXX",
  "phone_error": "Please enter your phone number",
  "phone_help": "We'll use this to contact you about your order",
  "delivery_address": "Delivery Address",
  "address_placeholder": "123 Main St, City, Country",
  "address_error": "Please enter your delivery address",
  "payment_method": "Payment Method",
  "payment_help": "For your safety, please wait until your order is confirmed before making any payment. We will contact you.",
  "select_payment": "Select a payment method",
  "payment_mobile_money": "Mobile Money (MTN, Orange, Moov)",
  "payment_cash": "Cash on Delivery",
  "payment_credit_card": "Credit Card (Stripe)",
  "payment_paypal": "PayPal",
  "payment_bank": "Bank Transfer",
  "payment_error": "Please select a payment method",
  "terms_agree": "I agree to the Terms of Service and Privacy Policy.",
  "terms_error": "You must agree to the terms to place an order",
  "order_notes": "Order Notes (Optional)",
  "notes_placeholder": "Special instructions for delivery...",
  "place_order": "Place Order",
  "order_summary": "Order Summary",
  "loading_cart": "Loading cart...",
  "subtotal": "Subtotal",
  "delivery_fee": "Delivery Fee",
  "total": "Total",
  "free": "Free",
  "cart_empty": "Your cart is empty",
  "browse_products": "Browse Products",
  "qty": "Qty",
  "cart_empty_error": "Your cart is empty",
  "please_login": "Please login to place an order",
  "placing_order": "Placing Order...",
  "order_failed": "Failed to place order. Please try again.",
  "order_placed_success": "Order placed successfully! 🎉",
  "order": "Order",
  "placed": "Placed",
  "thank_you": "Thank you",
  "your_order": "Your order",
  "totaling": "totaling",
  "has_been_received": "has been received.",
  "customer": "Customer",
  "email": "Email",
  "phone": "Phone",
  "address": "Address",
  "payment": "Payment",
  "notes": "Notes",
  "items": "Items",
  "contact_page_title": "Contact & Locate Us · Sucess Technology",
  "loading_info": "Loading contact information...",
  "contact_title": "Contact",
  "hero_description": "We're here to help you with any questions or concerns. Reach out to us through any of the channels below.",
  "loading_address": "Loading address...",
  "loading_hours": "Loading hours...",
  "shop_photo": "Shop Photo",
  "location_label": "Location",
  "map": "Map",
  "phone_label": "Phone",
  "loading": "Loading...",
  "whatsapp": "WhatsApp",
  "email_label": "Email",
  "send": "Send",
  "hours_label": "Business Hours",
  "open_now": "🟢 Open Now",
  "closed": "🔴 Closed",
  "store_label": "Store",
  "find_us": "Find Us Here",
  "loading_coords": "📍 Loading coordinates...",
  "open_maps": "Open in Google Maps",
  "store_description": "Additional information about the store.",
  "get_directions": "Get Directions",
  "call_store": "Call Store",
  "share_location": "Share Location",
  "browse_products": "Browse Products",
  "connect_social": "Connect with us on social media",
  "no_social": "No social links available",
  "ready_to_visit": "Ready to Visit Us?",
  "visit_us_text": "Come experience our products in person. We're excited to serve you!",
  "get_directions_cta": "Get Directions",
  "call_us_now": "Call Us Now",
  "default_description": "Your trusted partner for premium technology products and exceptional service.",
  "default_address": "Douala, Cameroon",
  "default_phone": " ",
  "default_email": "info@sucesstechnology.com",
  "default_hours": "Mon - Fri: 7:00 AM - 8:00 PM\nSun: Closed",
  "our_store": "Our Store",
  "visit_our_store": "Visit Our Store",
  "find_us_at": "Find us at",
  "location_copied": "Location link copied!",
  "locate_us": "Locate Us",
  "deals_page_title": "🔥 Deals & Offers · Sucess Technology",
  "limited_time_offers": "Limited Time Offers",
  "mega_deals": "Mega",
  "deals_of_day": "Deals",
  "of_the_day": "of the Day",
  "hero_description": "Grab the best offers on premium products. Discounts up to 70% on selected items. Hurry, these deals won't last!",
  "active_deals": "Active Deals",
  "max_savings": "Max Savings",
  "items_on_sale": "Items On Sale",
  "days": "Days",
  "hours": "Hours",
  "minutes": "Minutes",
  "seconds": "Seconds",
  "explore_deals": "Explore Deals",
  "percent_off": "70% OFF",
  "flash_sale": "Flash Sale",
  "limited_stock": "Limited Stock",
  "all_deals": "All Deals",
  "handpicked_offers": "Handpicked offers just for you",
  "filter_all": "All",
  "filter_mega": "🔥 Mega",
  "filter_hot": "⚡ Hot",
  "filter_new": "✨ New",
  "you_may_also_like": "You May Also Like",
  "no_deals_title": "No Deals Available",
  "no_deals_sub": "Check back soon for amazing offers!",
  "browse_products": "Browse Products",
  "badge_mega": "🔥 Mega",
  "badge_hot": "⚡ Hot",
  "badge_new": "✨ New",
  "badge_deal": "💸 Deal",
  "save_percent": "Save {0}%",
  "view_details": "View Details",
  "left_in_stock": "{0} left",
  "out_of_stock": "Out of Stock",
  "removed_from_wishlist": "Removed from wishlist",
  "added_to_wishlist": "Added to wishlist!",
  "wishlist_error": "Failed to update wishlist, please try again.",
   "recommended": "Recommended",
  "for_you_title": "For You",
  "showing_in": "Showing products in",
  "all": "All",
  "for_you": "For You",
  "see_all": "See All →",
  "view_all": "View All →",
  "deal": "🔥 Deal",
  "sold": "sold",
  "hot": "Hot",
  "new": "New",
  "items": "items",
  "no_categories": "No categories",
  "no_products": "No products in this category",
  "no_recommendations": "No recommendations",
  "load_error": "Failed to load data",
  "removed_wishlist": "Removed from wishlist",
  "added_wishlist": "Added to wishlist!",
  "failed": "Failed",
  "product_not_found_title": "Product Not Found",
  "product_not_found_sub": "We couldn't find the product you're looking for.",
  "return_to_store": "Return to Store",
  "home": "Home",
  "reviews": "Reviews",
  "deal_of_day": "🔥 Deal of the Day - Limited Time Offer!",
  "specifications": "Specifications",
  "quantity": "Quantity",
  "decrease": "−",
  "increase": "+",
  "add_to_cart": "Add to Cart",
  "wishlist": "Wishlist",
  "share": "Share",
  "special_deals": "Special Deals",
  "limited_time_offers": "🔥 Limited time offers",
  "customer_reviews": "Customer Reviews",
  "write_review": "✏️ Write a Review",
  "your_name": "Your name",
  "your_review": "Your review...",
  "submit_review": "Submit Review",
  "you_may_also_like": "🔄 You May Also Like",
  "loading_more_products": "Loading more products...",
  "footer_products": "Products",
  "footer_phone": "Phone",
  "footer_tablet": "Tablet",
  "footer_audio": "Audio",
  "footer_follow": "📱 Follow Us",
  "footer_about": "About",
  "about_us": "About Us",
  "press": "Press",
  "locate_us": "📍 Locate Us",
  "footer_contact": "📞 Contact",
  "copyright": "© 2024 Sucess Technology. All rights reserved.",
  "no_deals_available": "No deals available right now",
  "view_details": "View Details",
  "adding": "Adding...",
  "only_items_available": "Only ",
  "items_available": "items available",
  "added_to_cart": "Added to cart!",
  "removed_from_wishlist": "Removed from wishlist",
  "added_to_wishlist": "Added to wishlist!",
  "wishlist_error": "Error updating wishlist",
  "in_wishlist": "In Wishlist",
  "link_copied": "Link copied to clipboard!",
  "no_reviews_yet": "No reviews yet. Be the first to review!",
  "please_enter_name": "Please enter your name",
  "please_write_review": "Please write a review",
  "submitting": "Submitting...",
  "offline_mode": "Offline mode: Review saved locally",
  "network_error": "Network error: Review saved locally",
  "thank_you_review": "Thank you for your review! 🎉",
  "error_saving_review": "Error saving review. Saved locally.",
  "cart_empty": "Cart empty",
  "cart_cleared": "Cart cleared",
  "checkout_coming": "Checkout coming soon!",
  "save": "SAVE",
  "off": "OFF",
  "deal_of_day_text": "Deal of the Day",
  "no_description": "No description available.",
  "processor": "Processor",
  "operating_system": "Operating System",
  "stock_status": "Stock Status",
  "in_stock": "In Stock",
  "out_of_stock": "Out of Stock",
  "no_specs": "No specifications available.",
  "available": "available",
  "my_orders": "My Orders",
  "orders_count": "{0} orders",
  "tab_all": "All",
  "tab_pending": "Pending",
  "tab_confirmed": "Confirmed",
  "tab_processing": "Processing",
  "tab_shipped": "Shipped",
  "tab_delivered": "Delivered",
  "tab_cancelled": "Cancelled",
  "loading_orders": "Loading your orders...",
  "loading_order_details": "Loading order details...",
  "placed": "Placed",
  "confirmed": "Confirmed",
  "processing": "Processing",
  "done": "Done",
  "please_login": "Please log in to view this order.",
  "order_not_found": "Order not found",
  "order_not_belong": "This order does not belong to your account.",
  "please_login_title": "Please Login",
  "login_to_view_orders": "Login to view your orders.",
  "order_not_available": "This order is not available right now.",
  "no_orders_title": "No Orders Yet",
  "no_orders_sub": "Start shopping to see your orders here.",
  "failed_to_load_title": "Failed to Load Orders",
  "failed_to_load_sub": "Please try again later.",
  "orders": "order",
  "no_orders_status": "No orders with status ",
  "try_different_filter": "Try a different filter.",
  "more": "more",
  "item": "item",
  "browse_products": "Browse Products",
  "go_to_login": "Go to Login",
  "retry": "Retry",
  "order": "Order",
  "customer": "Customer",
  "email": "Email",
  "phone": "Phone",
  "address": "Address",
  "status": "Status",
  "date": "Date",
  "items": "Items",
  "total": "Total",
  "copy": "Copy",
  "order_total": "Order Total",
  "order_items": "Order Items",
  "notes": "Notes",
  "continue_shopping": "Continue Shopping",
  "contact_us": "Contact Us",
  "order_id_copied": "Order ID copied to clipboard!",
  "order_cancelled": "Order Cancelled",
  "return_policy_title": "Return & Refund Policy",
  "return_policy_sub": "We are committed to providing you with a satisfying shopping experience. If you need to return an item, we have implemented a clear and fair return policy to facilitate your experience.",
  "updated_january": "Updated January 2025",
  "change_mind_title": "Returns for Change of Mind or Size",
  "change_mind_sub": "You can return most items, with some exceptions",
  "not_eligible": "Not eligible:",
  "opened_sealed": "Opened sealed items (official brand seals or original packaging)",
  "mattresses_underwear": "Mattresses, underwear, swimwear",
  "tvs_appliances": "TVs & Large Appliances",
  "large_furniture": "Large stapled items (sofas, furniture)",
  "return_conditions": "Return Conditions:",
  "return_conditions_text": "You must return the item with its invoice and packaging in excellent condition.",
  "return_period": "Return Period:",
  "return_period_days": "7 business days",
  "from_delivery": "from delivery date to initiate your return.",
  "defective_title": "Returns for Defective Items",
  "defective_sub": "Defective, broken, non-functional, or counterfeit items",
  "defective_text": "Returns are accepted for all types of items, except for categories not eligible for return.",
  "return_deadline": "Return Deadline:",
  "return_deadline_days": "7 business days",
  "note": "Note:",
  "note_contact": "For categories not eligible for return, please contact our Customer Service.",
  "ineligible_title": "Categories Not Eligible for Return",
  "important": "⚠️ Important",
  "ineligible_mattresses": "Mattresses",
  "ineligible_printers": "Printers & Software",
  "ineligible_groceries": "Supermarkets & Groceries",
  "ineligible_underwear": "Underwear & Swimwear",
  "ineligible_beauty": "Beauty & Makeup",
  "ineligible_perfumes": "Perfumes & Wellness",
  "ineligible_events": "Events & Tickets",
  "ineligible_second_chance": "\"Second Chance\" Items",
  "second_chance_note": "Second Chance products are not refundable for simple change of mind, damage to packaging, or minor cosmetic defects, if clearly stated in the product description.",
  "important_info": "Important Information",
  "important_info_text": "⚠️ We recommend that you carefully check your items upon receipt to avoid any disputes. Categories not eligible for return upon receipt. If you have any questions about a specific product's return eligibility, please contact our customer service team.",
  "need_help": "Need Help?",
  "contact_team": "Contact our customer service team",
  "contact_us": "Contact Us",
  "call_us": "Call Us",
   "curated_for_you": "Curated Just For You",
  "discover": "Discover",
  "your": "Your",
  "perfect_picks": "Perfect Picks",
  "hero_description": "Handpicked products from your favorite brands and categories. Personalized recommendations updated daily.",
  "loading_recommendations": "Loading more recommendations...",
  "seen_all": "You've seen all our recommendations!",
  "check_back_later": "Check back later for new picks.",
  "brand": "Brand",
  "category": "Category",
  "products": "products",
  "deal": "🔥 Deal",
  "hot": "⚡ Hot",
  "new": "✨ New",
  "removed_wishlist": "Removed from wishlist",
  "added_wishlist": "Added to wishlist!",
  "wishlist_failed": "Failed to update wishlist",
  "curating_picks": "Curating your personalized picks...",
  "no_products_title": "No products available",
  "no_products_sub": "Check back later for personalized recommendations.",
   "return": "Return",
  "refund_policy": "Refund Policy",
  "hero_description": "We are committed to your satisfaction. Our 7-day guarantee ensures you can shop with confidence. If you're not completely happy with your purchase, we're here to help.",
  "updated_january": "Updated January 2025",
  "guarantee_title": "🛡️ 7-Day Satisfaction Guarantee",
  "guarantee_sub": "Not happy with your purchase? We'll make it right.",
  "guarantee_badge": "7 DAYS",
  "change_mind_title": "Returns for Change of Mind",
  "change_mind_sub": "You can return most items within 7 days",
  "not_eligible": "Not eligible:",
  "opened_sealed": "Opened sealed items",
  "underwear_swimwear": "Underwear, swimwear",
  "large_appliances": "Large appliances",
  "return_conditions": "Return Conditions:",
  "return_conditions_text": "Items must be returned with original invoice and packaging in excellent condition.",
  "return_period": "Return Period:",
  "return_period_days": "7 business days",
  "from_delivery": "from delivery date.",
  "defective_title": "Returns for Defective Items",
  "defective_sub": "Damaged, faulty, or non-functional items",
  "defective_text": "Returns accepted for all types of items, except items not eligible for return.",
  "return_conditions_text_defective": "Items must be returned with original invoice and packaging.",
  "return_deadline": "Return Deadline:",
  "return_deadline_days": "7 business days",
  "note": "Note:",
  "note_ineligible": "For ineligible items, please contact our Customer Service.",
  "not_eligible_title": "Items Not Eligible for Return",
  "important": "⚠️ Important",
  "excl_mattresses": "Mattresses",
  "excl_printers": "Printers & Software",
  "excl_groceries": "Groceries & Food",
  "excl_underwear": "Underwear & Swimwear",
  "excl_beauty": "Beauty & Makeup",
  "excl_perfumes": "Perfumes & Wellness",
  "excl_events": "Event Tickets",
  "excl_second_chance": "\"Second Chance\" Items",
  "second_chance_note": "Second Chance products are non-refundable for change of mind, packaging damage, or minor cosmetic defects as stated in the product description.",
  "return_process": "How to Return an Item",
  "step1_title": "Submit Return Request",
  "step1_desc": "Contact us within 7 days of delivery",
  "step2_title": "Pack Your Item",
  "step2_desc": "Use original packaging with invoice",
  "step3_title": "Ship It Back",
  "step3_desc": "Drop off at our designated collection point",
  "step4_title": "Get Refund",
  "step4_desc": "Refund processed within 5-7 business days",
  "important_info": "Important Information",
  "important_info_text": "⚠️ Please inspect your items immediately upon delivery to avoid any disputes. Items not eligible for return must be checked at the time of receipt. If you have any questions about a specific product's return eligibility, please contact our customer service team before purchasing.",
  "need_help": "Need Help?",
  "contact_team": "Contact our customer service team",
  "contact_us": "Contact Us",
  "call_us": "Call Us",
  "search_results_for": "Search Results for",
  "loading_results": "Loading results...",
  "search_again": "Search again...",
  "search": "Search",
  "filter": "Filter:",
  "filter_all": "All",
  "filter_phones": "Phones",
  "filter_laptops": "Laptops",
  "filter_tablets": "Tablets",
  "filter_audio": "Audio",
  "filter_accessories": "Accessories",
  "sort": "Sort:",
  "sort_relevance": "Relevance",
  "sort_price_asc": "Price: Low to High",
  "sort_price_desc": "Price: High to Low",
  "sort_newest": "Newest First",
  "sort_rating": "Highest Rated",
  "products_count": "0 products",
  "searching_products": "Searching for products...",
  "load_more": "Load More",
  "no_products_found": "No products found",
  "no_products_message": "We couldn't find any products matching",
  "browse_all": "Browse All Products",
  "clear_search": "Clear Search",
  "badge_deal": "🔥 Deal",
  "badge_hot": "⚡ Hot",
  "badge_new": "✨ New",
  "product": "product",
  "found_results": "Found",
  "results_for": "results for",
  "all_products": "All Products",
  "showing_all": "Showing all products",
  "removed_wishlist": "Removed from wishlist",
  "added_wishlist": "Added to wishlist!",
  "wishlist_failed": "Failed to update wishlist",
  "search_failed": "Failed to search products",
  "loading": "Loading...",
  "terms_and": "Terms &",
  "conditions": "Conditions",
  "terms_intro": "Please read these terms and conditions carefully before using our platform. By accessing or using our services, you agree to be bound by these terms.",
  "effective_date": "Effective January 2025",
  "last_updated": "Last Updated:",
  "table_of_contents": "Table of Contents",
  "toc_acceptance": "Acceptance of Terms",
  "toc_accounts": "User Accounts",
  "toc_orders": "Orders & Payments",
  "toc_shipping": "Shipping & Delivery",
  "toc_returns": "Returns & Refunds",
  "toc_product_info": "Product Information",
  "toc_intellectual": "Intellectual Property",
  "toc_privacy": "Privacy Policy",
  "toc_liability": "Limitation of Liability",
  "toc_changes": "Changes to Terms",
  "toc_contact": "Contact Us",
  "sec1_title": "Acceptance of Terms",
  "sec1_text": "By using the {0} platform, you agree to comply with and be bound by these Terms & Conditions. If you do not agree to these terms, please do not use our services.",
  "sec1_bullet1": "You must be at least 18 years old to use our services.",
  "sec1_bullet2": "You agree to provide accurate and complete information when using our platform.",
  "sec1_bullet3": "You are responsible for maintaining the confidentiality of your account credentials.",
  "sec1_bullet4": "We reserve the right to terminate accounts that violate these terms.",
  "important_label": "ℹ️ Important",
  "sec1_highlight": "By continuing to use our platform, you acknowledge that you have read, understood, and agree to be bound by these terms.",
  "sec2_title": "User Accounts",
  "sec2_text": "To access certain features of our platform, you may be required to create a user account. You are responsible for all activities that occur under your account.",
  "sec2_bullet1": "You must provide accurate and complete registration information.",
  "sec2_bullet2": "You are responsible for keeping your password secure and confidential.",
  "sec2_bullet3": "You must notify us immediately of any unauthorized use of your account.",
  "sec2_bullet4": "We reserve the right to suspend or terminate accounts that violate our policies.",
  "sec2_bullet5": "You may not create multiple accounts for fraudulent purposes.",
  "sec3_title": "Orders & Payments",
  "sec3_text": "All orders placed through our platform are subject to acceptance and availability. We reserve the right to refuse or cancel any order for any reason.",
  "sec3_bullet1": "Prices are subject to change without prior notice.",
  "sec3_bullet2": "We accept various payment methods as displayed on our platform.",
  "sec3_bullet3": "All payments are processed securely through our trusted payment partners.",
  "sec3_bullet4": "You agree to provide accurate and complete payment information.",
  "sec3_bullet5": "We reserve the right to cancel orders if payment is not received or verified.",
  "payment_security_label": "💳 Payment Security",
  "payment_security_text": "All transactions are encrypted and processed securely. We do not store your full payment details on our servers.",
  "sec4_title": "Shipping & Delivery",
  "sec4_text": "We strive to deliver your orders in a timely and efficient manner. Delivery times are estimated and may vary depending on your location.",
  "sec4_bullet1": "Shipping costs are calculated based on weight, dimensions, and destination.",
  "sec4_bullet2": "Delivery times are estimates and not guaranteed.",
  "sec4_bullet3": "We are not responsible for delays caused by customs or shipping carriers.",
  "sec4_bullet4": "You are responsible for providing accurate delivery information.",
  "sec4_bullet5": "Risk of loss passes to you upon delivery.",
  "sec5_title": "Returns & Refunds",
  "sec5_text": "We want you to be completely satisfied with your purchase. Please refer to our Return Policy for detailed information.",
  "sec5_bullet1": "Returns must be initiated within 7 business days of delivery.",
  "sec5_bullet2": "Items must be returned in their original packaging and condition.",
  "sec5_bullet3": "Refunds are processed to the original payment method.",
  "sec5_bullet4": "Some items are not eligible for return (see Return Policy).",
  "sec5_bullet5": "Shipping costs are non-refundable unless the return is due to our error.",
  "return_policy_label": "📋 Return Policy",
  "sec5_highlight": "For full details, please visit our Return Policy page.",
  "return_policy_link": "Return Policy page",
  "sec6_title": "Product Information",
  "sec6_text": "We strive to provide accurate and up-to-date product information. However, we do not guarantee that product descriptions, images, or specifications are error-free.",
  "sec6_bullet1": "Product images are for illustrative purposes only.",
  "sec6_bullet2": "Actual products may vary slightly from images shown.",
  "sec6_bullet3": "We reserve the right to correct errors in pricing or product information.",
  "sec6_bullet4": "Product availability is subject to change without notice.",
  "sec6_bullet5": "All products are subject to manufacturer warranties where applicable.",
  "sec7_title": "Intellectual Property",
  "sec7_text": "All content on our platform, including text, images, logos, and software, is the property of {0} and is protected by copyright and intellectual property laws.",
  "sec7_bullet1": "You may not reproduce, distribute, or modify any content without our permission.",
  "sec7_bullet2": "All trademarks and logos are the property of their respective owners.",
  "sec7_bullet3": "Unauthorized use of our content may result in legal action.",
  "sec7_bullet4": "You are granted a limited license to access and use our platform for personal, non-commercial purposes.",
  "sec8_title": "Privacy Policy",
  "sec8_text": "Your privacy is important to us. Please review our Privacy Policy to understand how we collect, use, and protect your personal information.",
  "sec8_bullet1": "We collect personal information to provide and improve our services.",
  "sec8_bullet2": "We do not sell or share your personal information with third parties without your consent.",
  "sec8_bullet3": "We implement security measures to protect your data.",
  "sec8_bullet4": "You have the right to access, modify, or delete your personal information.",
  "sec8_bullet5": "Cookies are used to enhance your browsing experience.",
  "privacy_matters_label": "🔒 Your Privacy Matters",
  "sec9_title": "Limitation of Liability",
  "sec9_text": "{0} is not liable for any damages arising from the use of our platform or products, to the fullest extent permitted by law.",
  "sec9_bullet1": "We are not responsible for indirect, incidental, or consequential damages.",
  "sec9_bullet2": "Our liability is limited to the purchase price of the product.",
  "sec9_bullet3": "We do not warrant that our platform will be error-free or uninterrupted.",
  "sec9_bullet4": "We are not responsible for third-party content or services.",
  "sec9_bullet5": "Some jurisdictions do not allow the exclusion of certain warranties, so this limitation may not apply to you.",
  "sec11_title": "Changes to Terms",
  "sec11_text": "We reserve the right to modify these Terms & Conditions at any time. Changes will be effective immediately upon posting on our platform.",
  "sec11_bullet1": "We will notify users of significant changes via email or platform notification.",
  "sec11_bullet2": "Your continued use of our platform constitutes acceptance of the revised terms.",
  "sec11_bullet3": "It is your responsibility to review these terms periodically.",
  "sec11_bullet4": "The date of the last revision is indicated at the top of this page.",
  "sec12_title": "Contact Us",
  "sec12_text": "If you have any questions, concerns, or comments about these Terms & Conditions, please feel free to contact us.",
  "email_label": "Email",
  "phone_label": "Phone",
  "address_label": "Address",
  "hours_label": "Business Hours",
  "help_label": "📞 We're Here to Help",
  "sec12_highlight": "Our customer service team is available to assist you with any questions or concerns. Visit our Contact page for more ways to reach us.",
  "contact_page_link": "Visit our Contact page",
  "accept_text": "By using our platform, you agree to these Terms & Conditions",
  "accept_btn": "I Accept",
  "decline_btn": "Decline",
  "thank_you_accept": "Thank you for accepting our Terms & Conditions!",
  "accepted": "Accepted",
  "must_accept": "You must accept the Terms & Conditions to use our platform.",
  "already_accepted": "Already Accepted",
  "effective": "Effective",
  

    },
    fr: {
         "terms_and": "Conditions",
  "conditions": "générales",
  "terms_intro": "Veuillez lire attentivement ces conditions générales avant d'utiliser notre plateforme. En accédant ou en utilisant nos services, vous acceptez d'être lié par ces conditions.",
  "effective_date": "En vigueur à partir de janvier 2025",
  "last_updated": "Dernière mise à jour :",
  "table_of_contents": "Table des matières",
  "toc_acceptance": "Acceptation des conditions",
  "toc_accounts": "Comptes utilisateurs",
  "toc_orders": "Commandes et paiements",
  "toc_shipping": "Expédition et livraison",
  "toc_returns": "Retours et remboursements",
  "toc_product_info": "Informations sur les produits",
  "toc_intellectual": "Propriété intellectuelle",
  "toc_privacy": "Politique de confidentialité",
  "toc_liability": "Limitation de responsabilité",
  "toc_changes": "Modifications des conditions",
  "toc_contact": "Contactez-nous",
  "sec1_title": "Acceptation des conditions",
  "sec1_text": "En utilisant la plateforme {0}, vous acceptez de vous conformer et d'être lié par ces conditions générales. Si vous n'acceptez pas ces conditions, veuillez ne pas utiliser nos services.",
  "sec1_bullet1": "Vous devez avoir au moins 18 ans pour utiliser nos services.",
  "sec1_bullet2": "Vous acceptez de fournir des informations exactes et complètes lors de l'utilisation de notre plateforme.",
  "sec1_bullet3": "Vous êtes responsable de la confidentialité de vos identifiants de compte.",
  "sec1_bullet4": "Nous nous réservons le droit de résilier les comptes qui violent ces conditions.",
  "important_label": "ℹ️ Important",
  "sec1_highlight": "En continuant à utiliser notre plateforme, vous reconnaissez avoir lu, compris et accepté d'être lié par ces conditions.",
  "sec2_title": "Comptes utilisateurs",
  "sec2_text": "Pour accéder à certaines fonctionnalités de notre plateforme, vous devrez peut-être créer un compte utilisateur. Vous êtes responsable de toutes les activités effectuées sous votre compte.",
  "sec2_bullet1": "Vous devez fournir des informations d'inscription exactes et complètes.",
  "sec2_bullet2": "Vous êtes responsable de la sécurité et de la confidentialité de votre mot de passe.",
  "sec2_bullet3": "Vous devez nous informer immédiatement de toute utilisation non autorisée de votre compte.",
  "sec2_bullet4": "Nous nous réservons le droit de suspendre ou de résilier les comptes qui violent nos politiques.",
  "sec2_bullet5": "Vous ne pouvez pas créer plusieurs comptes à des fins frauduleuses.",
  "sec3_title": "Commandes et paiements",
  "sec3_text": "Toutes les commandes passées sur notre plateforme sont soumises à acceptation et disponibilité. Nous nous réservons le droit de refuser ou d'annuler toute commande pour quelque raison que ce soit.",
  "sec3_bullet1": "Les prix sont sujets à modification sans préavis.",
  "sec3_bullet2": "Nous acceptons divers modes de paiement comme indiqué sur notre plateforme.",
  "sec3_bullet3": "Tous les paiements sont traités en toute sécurité via nos partenaires de paiement de confiance.",
  "sec3_bullet4": "Vous acceptez de fournir des informations de paiement exactes et complètes.",
  "sec3_bullet5": "Nous nous réservons le droit d'annuler les commandes si le paiement n'est pas reçu ou vérifié.",
  "payment_security_label": "💳 Sécurité des paiements",
  "payment_security_text": "Toutes les transactions sont cryptées et traitées en toute sécurité. Nous ne stockons pas vos coordonnées de paiement complètes sur nos serveurs.",
  "sec4_title": "Expédition et livraison",
  "sec4_text": "Nous nous efforçons de livrer vos commandes dans les délais et de manière efficace. Les délais de livraison sont estimés et peuvent varier en fonction de votre localisation.",
  "sec4_bullet1": "Les frais d'expédition sont calculés en fonction du poids, des dimensions et de la destination.",
  "sec4_bullet2": "Les délais de livraison sont des estimations et ne sont pas garantis.",
  "sec4_bullet3": "Nous ne sommes pas responsables des retards causés par les douanes ou les transporteurs.",
  "sec4_bullet4": "Vous êtes responsable de fournir des informations de livraison précises.",
  "sec4_bullet5": "Le risque de perte vous est transféré à la livraison.",
  "sec5_title": "Retours et remboursements",
  "sec5_text": "Nous voulons que vous soyez entièrement satisfait de votre achat. Veuillez consulter notre politique de retour pour plus d'informations.",
  "sec5_bullet1": "Les retours doivent être initiés dans les 7 jours ouvrables suivant la livraison.",
  "sec5_bullet2": "Les articles doivent être retournés dans leur emballage d'origine et en bon état.",
  "sec5_bullet3": "Les remboursements sont effectués sur le mode de paiement d'origine.",
  "sec5_bullet4": "Certains articles ne sont pas éligibles au retour (voir la politique de retour).",
  "sec5_bullet5": "Les frais d'expédition ne sont pas remboursables, sauf si le retour est dû à notre erreur.",
  "return_policy_label": "📋 Politique de retour",
  "sec5_highlight": "Pour plus de détails, veuillez visiter notre page Politique de retour.",
  "return_policy_link": "page Politique de retour",
  "sec6_title": "Informations sur les produits",
  "sec6_text": "Nous nous efforçons de fournir des informations sur les produits exactes et à jour. Cependant, nous ne garantissons pas que les descriptions, images ou spécifications des produits sont exemptes d'erreurs.",
  "sec6_bullet1": "Les images des produits sont fournies à titre indicatif uniquement.",
  "sec6_bullet2": "Les produits réels peuvent légèrement varier par rapport aux images présentées.",
  "sec6_bullet3": "Nous nous réservons le droit de corriger les erreurs de prix ou d'informations sur les produits.",
  "sec6_bullet4": "La disponibilité des produits est sujette à modification sans préavis.",
  "sec6_bullet5": "Tous les produits sont soumis aux garanties du fabricant le cas échéant.",
  "sec7_title": "Propriété intellectuelle",
  "sec7_text": "Tout le contenu de notre plateforme, y compris les textes, images, logos et logiciels, est la propriété de {0} et est protégé par les lois sur le droit d'auteur et la propriété intellectuelle.",
  "sec7_bullet1": "Vous ne pouvez pas reproduire, distribuer ou modifier un contenu sans notre autorisation.",
  "sec7_bullet2": "Toutes les marques et logos sont la propriété de leurs propriétaires respectifs.",
  "sec7_bullet3": "L'utilisation non autorisée de notre contenu peut entraîner des poursuites judiciaires.",
  "sec7_bullet4": "Vous bénéficiez d'une licence limitée pour accéder à notre plateforme et l'utiliser à des fins personnelles et non commerciales.",
  "sec8_title": "Politique de confidentialité",
  "sec8_text": "Votre vie privée est importante pour nous. Veuillez consulter notre politique de confidentialité pour comprendre comment nous collectons, utilisons et protégeons vos informations personnelles.",
  "sec8_bullet1": "Nous collectons des informations personnelles pour fournir et améliorer nos services.",
  "sec8_bullet2": "Nous ne vendons ni ne partageons vos informations personnelles avec des tiers sans votre consentement.",
  "sec8_bullet3": "Nous mettons en œuvre des mesures de sécurité pour protéger vos données.",
  "sec8_bullet4": "Vous avez le droit d'accéder, de modifier ou de supprimer vos informations personnelles.",
  "sec8_bullet5": "Les cookies sont utilisés pour améliorer votre expérience de navigation.",
  "privacy_matters_label": "🔒 Votre vie privée compte",
  "sec9_title": "Limitation de responsabilité",
  "sec9_text": "{0} n'est pas responsable des dommages découlant de l'utilisation de notre plateforme ou de nos produits, dans la mesure maximale autorisée par la loi.",
  "sec9_bullet1": "Nous ne sommes pas responsables des dommages indirects, accessoires ou consécutifs.",
  "sec9_bullet2": "Notre responsabilité est limitée au prix d'achat du produit.",
  "sec9_bullet3": "Nous ne garantissons pas que notre plateforme sera exempte d'erreurs ou ininterrompue.",
  "sec9_bullet4": "Nous ne sommes pas responsables du contenu ou des services de tiers.",
  "sec9_bullet5": "Certaines juridictions n'autorisent pas l'exclusion de certaines garanties, cette limitation peut donc ne pas s'appliquer à vous.",
  "sec11_title": "Modifications des conditions",
  "sec11_text": "Nous nous réservons le droit de modifier ces conditions générales à tout moment. Les modifications entreront en vigueur immédiatement après leur publication sur notre plateforme.",
  "sec11_bullet1": "Nous informerons les utilisateurs des changements importants par e-mail ou par notification sur la plateforme.",
  "sec11_bullet2": "Votre utilisation continue de notre plateforme constitue une acceptation des conditions révisées.",
  "sec11_bullet3": "Il est de votre responsabilité de consulter périodiquement ces conditions.",
  "sec11_bullet4": "La date de la dernière révision est indiquée en haut de cette page.",
  "sec12_title": "Contactez-nous",
  "sec12_text": "Si vous avez des questions, des préoccupations ou des commentaires concernant ces conditions générales, n'hésitez pas à nous contacter.",
  "email_label": "E-mail",
  "phone_label": "Téléphone",
  "address_label": "Adresse",
  "hours_label": "Horaires d'ouverture",
  "help_label": "📞 Nous sommes là pour vous aider",
  "sec12_highlight": "Notre équipe de service client est disponible pour vous aider avec toutes vos questions ou préoccupations. Visitez notre page Contact pour plus de moyens de nous joindre.",
  "contact_page_link": "Visitez notre page Contact",
  "accept_text": "En utilisant notre plateforme, vous acceptez ces conditions générales",
  "accept_btn": "J'accepte",
  "decline_btn": "Refuser",
  "thank_you_accept": "Merci d'avoir accepté nos conditions générales !",
  "accepted": "Accepté",
  "must_accept": "Vous devez accepter les conditions générales pour utiliser notre plateforme.",
  "already_accepted": "Déjà accepté",
  "effective": "En vigueur",
         "search_results_for": "Résultats de recherche pour",
  "loading_results": "Chargement des résultats...",
  "search_again": "Rechercher à nouveau...",
  "search": "Rechercher",
  "filter": "Filtrer :",
  "filter_all": "Tout",
  "filter_phones": "Téléphones",
  "filter_laptops": "Ordinateurs portables",
  "filter_tablets": "Tablettes",
  "filter_audio": "Audio",
  "filter_accessories": "Accessoires",
  "sort": "Trier :",
  "sort_relevance": "Pertinence",
  "sort_price_asc": "Prix : Croissant",
  "sort_price_desc": "Prix : Décroissant",
  "sort_newest": "Plus récents",
  "sort_rating": "Mieux notés",
  "products_count": "0 produits",
  "searching_products": "Recherche de produits...",
  "load_more": "Charger plus",
  "no_products_found": "Aucun produit trouvé",
  "no_products_message": "Nous n'avons trouvé aucun produit correspondant à",
  "browse_all": "Parcourir tous les produits",
  "clear_search": "Effacer la recherche",
  "badge_deal": "🔥 Offre",
  "badge_hot": "⚡ Tendance",
  "badge_new": "✨ Nouveau",
  "product": "produit",
  "found_results": "Trouvés",
  "results_for": "résultats pour",
  "all_products": "Tous les produits",
  "showing_all": "Affichage de tous les produits",
  "removed_wishlist": "Retiré de la liste de souhaits",
  "added_wishlist": "Ajouté à la liste de souhaits !",
  "wishlist_failed": "Échec de la mise à jour de la liste de souhaits",
  "search_failed": "Échec de la recherche de produits",
  "loading": "Chargement...",
        "return": "Retour",
  "refund_policy": "Politique de remboursement",
  "hero_description": "Nous nous engageons pour votre satisfaction. Notre garantie de 7 jours vous permet de faire vos achats en toute confiance. Si vous n'êtes pas entièrement satisfait de votre achat, nous sommes là pour vous aider.",
  "updated_january": "Mis à jour en janvier 2025",
  "guarantee_title": "🛡️ Garantie de satisfaction de 7 jours",
  "guarantee_sub": "Pas satisfait de votre achat ? Nous allons arranger les choses.",
  "guarantee_badge": "7 JOURS",
  "change_mind_title": "Retours pour changement d'avis",
  "change_mind_sub": "Vous pouvez retourner la plupart des articles dans les 7 jours",
  "not_eligible": "Non éligible :",
  "opened_sealed": "Articles scellés ouverts",
  "underwear_swimwear": "Sous-vêtements, maillots de bain",
  "large_appliances": "Gros appareils électroménagers",
  "return_conditions": "Conditions de retour :",
  "return_conditions_text": "Les articles doivent être retournés avec la facture originale et l'emballage en excellent état.",
  "return_period": "Délai de retour :",
  "return_period_days": "7 jours ouvrables",
  "from_delivery": "à compter de la date de livraison.",
  "defective_title": "Retours pour articles défectueux",
  "defective_sub": "Articles endommagés, défectueux ou non fonctionnels",
  "defective_text": "Retours acceptés pour tous les types d'articles, sauf les articles non éligibles au retour.",
  "return_conditions_text_defective": "Les articles doivent être retournés avec la facture originale et l'emballage.",
  "return_deadline": "Délai de retour :",
  "return_deadline_days": "7 jours ouvrables",
  "note": "Remarque :",
  "note_ineligible": "Pour les articles non éligibles, veuillez contacter notre Service Client.",
  "not_eligible_title": "Articles non éligibles au retour",
  "important": "⚠️ Important",
  "excl_mattresses": "Matelas",
  "excl_printers": "Imprimantes et logiciels",
  "excl_groceries": "Épicerie et alimentation",
  "excl_underwear": "Sous-vêtements et maillots de bain",
  "excl_beauty": "Beauté et maquillage",
  "excl_perfumes": "Parfums et bien-être",
  "excl_events": "Billets d'événements",
  "excl_second_chance": "Articles \"Seconde Chance\"",
  "second_chance_note": "Les produits Seconde Chance ne sont pas remboursables pour changement d'avis, dommages à l'emballage ou défauts cosmétiques mineurs comme indiqué dans la description du produit.",
  "return_process": "Comment retourner un article",
  "step1_title": "Soumettre une demande de retour",
  "step1_desc": "Contactez-nous dans les 7 jours suivant la livraison",
  "step2_title": "Emballez votre article",
  "step2_desc": "Utilisez l'emballage d'origine avec la facture",
  "step3_title": "Retournez-le",
  "step3_desc": "Déposez-le à notre point de collecte désigné",
  "step4_title": "Recevez votre remboursement",
  "step4_desc": "Remboursement traité sous 5 à 7 jours ouvrables",
  "important_info": "Informations importantes",
  "important_info_text": "⚠️ Veuillez inspecter vos articles immédiatement à la réception pour éviter tout litige. Les articles non éligibles au retour doivent être vérifiés au moment de la réception. Si vous avez des questions sur l'éligibilité au retour d'un produit spécifique, veuillez contacter notre équipe de service client avant d'acheter.",
  "need_help": "Besoin d'aide ?",
  "contact_team": "Contactez notre équipe de service client",
  "contact_us": "Contactez-nous",
  "call_us": "Appelez-nous",
        "curated_for_you": "Sélectionné spécialement pour vous",
  "discover": "Découvrez",
  "your": "Vos",
  "perfect_picks": "Picks Parfaits",
  "hero_description": "Des produits sélectionnés à la main parmi vos marques et catégories préférées. Des recommandations personnalisées mises à jour quotidiennement.",
  "loading_recommendations": "Chargement de plus de recommandations...",
  "seen_all": "Vous avez vu toutes nos recommandations !",
  "check_back_later": "Revenez plus tard pour de nouvelles sélections.",
  "brand": "Marque",
  "category": "Catégorie",
  "products": "produits",
  "deal": "🔥 Offre",
  "hot": "⚡ Tendance",
  "new": "✨ Nouveau",
  "removed_wishlist": "Retiré de la liste de souhaits",
  "added_wishlist": "Ajouté à la liste de souhaits !",
  "wishlist_failed": "Échec de la mise à jour de la liste de souhaits",
  "curating_picks": "Préparation de vos sélections personnalisées...",
  "no_products_title": "Aucun produit disponible",
  "no_products_sub": "Revenez plus tard pour des recommandations personnalisées.",
        "return_policy_title": "Politique de retour et de remboursement",
  "return_policy_sub": "Nous nous engageons à vous offrir une expérience d'achat satisfaisante. Si vous devez retourner un article, nous avons mis en place une politique de retour claire et équitable pour faciliter votre expérience.",
  "updated_january": "Mis à jour en janvier 2025",
  "change_mind_title": "Retours pour changement d'avis ou de taille",
  "change_mind_sub": "Vous pouvez retourner la plupart des articles, avec quelques exceptions",
  "not_eligible": "Non éligible :",
  "opened_sealed": "Articles scellés ouverts (sceaux officiels de la marque ou emballage d'origine)",
  "mattresses_underwear": "Matelas, sous-vêtements, maillots de bain",
  "tvs_appliances": "Téléviseurs et gros appareils électroménagers",
  "large_furniture": "Grands articles agrafés (canapés, meubles)",
  "return_conditions": "Conditions de retour :",
  "return_conditions_text": "Vous devez retourner l'article avec sa facture et son emballage en excellent état.",
  "return_period": "Délai de retour :",
  "return_period_days": "7 jours ouvrables",
  "from_delivery": "à compter de la date de livraison pour initier votre retour.",
  "defective_title": "Retours pour articles défectueux",
  "defective_sub": "Articles défectueux, cassés, non fonctionnels ou contrefaits",
  "defective_text": "Les retours sont acceptés pour tous les types d'articles, sauf pour les catégories non éligibles au retour.",
  "return_deadline": "Délai de retour :",
  "return_deadline_days": "7 jours ouvrables",
  "note": "Remarque :",
  "note_contact": "Pour les catégories non éligibles au retour, veuillez contacter notre Service Client.",
  "ineligible_title": "Catégories non éligibles au retour",
  "important": "⚠️ Important",
  "ineligible_mattresses": "Matelas",
  "ineligible_printers": "Imprimantes et logiciels",
  "ineligible_groceries": "Supermarchés et épiceries",
  "ineligible_underwear": "Sous-vêtements et maillots de bain",
  "ineligible_beauty": "Beauté et maquillage",
  "ineligible_perfumes": "Parfums et bien-être",
  "ineligible_events": "Événements et billets",
  "ineligible_second_chance": "Articles \"Seconde Chance\"",
  "second_chance_note": "Les produits Seconde Chance ne sont pas remboursables pour un simple changement d'avis, des dommages à l'emballage ou des défauts cosmétiques mineurs, si cela est clairement indiqué dans la description du produit.",
  "important_info": "Informations importantes",
  "important_info_text": "⚠️ Nous vous recommandons de vérifier soigneusement vos articles à la réception pour éviter tout litige. Les catégories non éligibles au retour à la réception. Si vous avez des questions sur l'éligibilité au retour d'un produit spécifique, veuillez contacter notre équipe de service client.",
  "need_help": "Besoin d'aide ?",
  "contact_team": "Contactez notre équipe de service client",
  "contact_us": "Contactez-nous",
  "call_us": "Appelez-nous",
        "my_orders": "Mes commandes",
  "orders_count": "{0} commandes",
  "tab_all": "Tout",
  "tab_pending": "En attente",
  "tab_confirmed": "Confirmé",
  "tab_processing": "En traitement",
  "tab_shipped": "Expédié",
  "tab_delivered": "Livré",
  "tab_cancelled": "Annulé",
  "loading_orders": "Chargement de vos commandes...",
  "loading_order_details": "Chargement des détails de la commande...",
  "placed": "Passée",
  "confirmed": "Confirmée",
  "processing": "En traitement",
  "done": "Terminée",
  "please_login": "Veuillez vous connecter pour voir cette commande.",
  "order_not_found": "Commande non trouvée",
  "order_not_belong": "Cette commande n'appartient pas à votre compte.",
  "please_login_title": "Veuillez vous connecter",
  "login_to_view_orders": "Connectez-vous pour voir vos commandes.",
  "order_not_available": "Cette commande n'est pas disponible pour le moment.",
  "no_orders_title": "Aucune commande pour l'instant",
  "no_orders_sub": "Commencez à magasiner pour voir vos commandes ici.",
  "failed_to_load_title": "Échec du chargement des commandes",
  "failed_to_load_sub": "Veuillez réessayer plus tard.",
  "orders": "commande",
  "no_orders_status": "Aucune commande avec le statut",
  "try_different_filter": "Essayez un autre filtre.",
  "more": "plus",
  "item": "article",
  "browse_products": "Parcourir les produits",
  "go_to_login": "Aller à la connexion",
  "retry": "Réessayer",
  "order": "Commande",
  "customer": "Client",
  "email": "E-mail",
  "phone": "Téléphone",
  "address": "Adresse",
  "status": "Statut",
  "date": "Date",
  "items": "Articles",
  "total": "Total",
  "copy": "Copier",
  "order_total": "Total de la commande",
  "order_items": "Articles de la commande",
  "notes": "Notes",
  "continue_shopping": "Continuer les achats",
  "contact_us": "Contactez-nous",
  "order_id_copied": "ID de commande copié dans le presse-papiers !",
  "order_cancelled": "Commande annulée",
        "product_not_found_title": "Produit non trouvé",
  "product_not_found_sub": "Nous n'avons pas trouvé le produit que vous recherchez.",
  "return_to_store": "Retourner au magasin",
  "home": "Accueil",
  "reviews": "Avis",
  "deal_of_day": "🔥 Offre du jour - Offre à durée limitée !",
  "specifications": "Spécifications",
  "quantity": "Quantité :",
  "decrease": "−",
  "increase": "+",
  "add_to_cart": "Ajouter au panier",
  "wishlist": "Liste de souhaits",
  "share": "Partager",
  "special_deals": "Offres spéciales",
  "limited_time_offers": "🔥 Offres à durée limitée",
  "customer_reviews": "Avis clients",
  "write_review": "✏️ Rédiger un avis",
  "your_name": "Votre nom",
  "your_review": "Votre avis...",
  "submit_review": "Soumettre l'avis",
  "you_may_also_like": "🔄 Vous aimerez aussi",
  "loading_more_products": "Chargement de plus de produits...",
  "footer_products": "Produits",
  "footer_phone": "Téléphone",
  "footer_tablet": "Tablette",
  "footer_audio": "Audio",
  "footer_follow": "📱 Suivez-nous",
  "footer_about": "À propos",
  "about_us": "À propos de nous",
  "press": "Presse",
  "locate_us": "📍 Nous trouver",
  "footer_contact": "📞 Contact",
  "copyright": "© 2024 Sucess Technology. Tous droits réservés.",
  "no_deals_available": "Aucune offre disponible pour le moment",
  "view_details": "Voir les détails",
  "adding": "Ajout en cours...",
  "only_items_available": "Seulement ",
  "items_available": "articles disponibles",
  "added_to_cart": "Ajouté au panier !",
  "removed_from_wishlist": "Retiré de la liste de souhaits",
  "added_to_wishlist": "Ajouté à la liste de souhaits !",
  "wishlist_error": "Erreur de mise à jour de la liste de souhaits",
  "in_wishlist": "Dans la liste de souhaits",
  "link_copied": "Lien copié dans le presse-papiers !",
  "no_reviews_yet": "Aucun avis pour le moment. Soyez le premier à donner votre avis !",
  "please_enter_name": "Veuillez entrer votre nom",
  "please_write_review": "Veuillez rédiger un avis",
  "submitting": "Soumission en cours...",
  "offline_mode": "Mode hors ligne : Avis sauvegardé localement",
  "network_error": "Erreur réseau : Avis sauvegardé localement",
  "thank_you_review": "Merci pour votre avis ! 🎉",
  "error_saving_review": "Erreur lors de l'enregistrement de l'avis. Sauvegardé localement.",
  "cart_empty": "Panier vide",
  "cart_cleared": "Panier vidé",
  "checkout_coming": "Paiement bientôt disponible !",
  "save": "ÉCONOMISEZ",
  "off": "DE RÉDUCTION",
  "deal_of_day_text": "Offre du jour",
  "no_description": "Aucune description disponible.",
  "processor": "Processeur",
  "operating_system": "Système d'exploitation",
  "stock_status": "État du stock",
  "in_stock": "En stock",
  "out_of_stock": "Rupture de stock",
  "no_specs": "Aucune spécification disponible.",
  "available": "disponible",
        "recommended": "Recommandé",
  "for_you_title": "Pour vous",
  "showing_in": "Affichage des produits dans",
  "all": "Tout",
  "for_you": "Pour vous",
  "see_all": "Voir tout →",
  "view_all": "Voir tout →",
  "deal": "🔥 Offre",
  "sold": "vendus",
  "hot": "Tendance",
  "new": "Nouveau",
  "items": "articles",
  "no_categories": "Aucune catégorie",
  "no_products": "Aucun produit dans cette catégorie",
  "no_recommendations": "Aucune recommandation",
  "load_error": "Échec du chargement des données",
  "removed_wishlist": "Retiré de la liste de souhaits",
  "added_wishlist": "Ajouté à la liste de souhaits !",
  "failed": "Échec",
        "deals_page_title": "🔥 Offres & Promotions · Sucess Technology",
  "limited_time_offers": "Offres à durée limitée",
  "mega_deals": "Méga",
  "deals_of_day": "Offres",
  "of_the_day": "du Jour",
  "hero_description": "Profitez des meilleures offres sur les produits premium. Réductions jusqu'à 70% sur les articles sélectionnés. Dépêchez-vous, ces offres ne dureront pas !",
  "active_deals": "Offres Actives",
  "max_savings": "Économies Max",
  "items_on_sale": "Articles en Solde",
  "days": "Jours",
  "hours": "Heures",
  "minutes": "Minutes",
  "seconds": "Secondes",
  "explore_deals": "Explorer les Offres",
  "percent_off": "70% DE RÉDUCTION",
  "flash_sale": "Vente Flash",
  "limited_stock": "Stock Limité",
  "all_deals": "Toutes les Offres",
  "handpicked_offers": "Des offres sélectionnées pour vous",
  "filter_all": "Tout",
  "filter_mega": "🔥 Méga",
  "filter_hot": "⚡ Tendance",
  "filter_new": "✨ Nouveau",
  "you_may_also_like": "Vous aimerez aussi",
  "no_deals_title": "Aucune offre disponible",
  "no_deals_sub": "Revenez bientôt pour des offres incroyables !",
  "browse_products": "Parcourir les produits",
  "badge_mega": "🔥 Méga",
  "badge_hot": "⚡ Tendance",
  "badge_new": "✨ Nouveau",
  "badge_deal": "💸 Offre",
  "save_percent": "Économisez {0}%",
  "view_details": "Voir les détails",
  "left_in_stock": "{0} restant",
  "out_of_stock": "Rupture de stock",
  "removed_from_wishlist": "Retiré de la liste de souhaits",
  "added_to_wishlist": "Ajouté à la liste de souhaits !",
  "wishlist_error": "Échec de la mise à jour de la liste de souhaits",
        "contact_page_title": "Contact & Nous trouver · Sucess Technology",
  "loading_info": "Chargement des informations de contact...",
  "contact_title": "Contact",
  "hero_description": "Nous sommes là pour vous aider avec toutes vos questions ou préoccupations. Contactez-nous via l'un des canaux ci-dessous.",
  "loading_address": "Chargement de l'adresse...",
  "loading_hours": "Chargement des horaires...",
  "shop_photo": "Photo du magasin",
  "location_label": "Emplacement",
  "map": "Carte",
  "phone_label": "Téléphone",
  "loading": "Chargement...",
  "whatsapp": "WhatsApp",
  "email_label": "E-mail",
  "send": "Envoyer",
  "hours_label": "Horaires d'ouverture",
  "open_now": "🟢 Ouvert maintenant",
  "closed": "🔴 Fermé",
  "store_label": "Magasin",
  "find_us": "Trouvez-nous ici",
  "loading_coords": "📍 Chargement des coordonnées...",
  "open_maps": "Ouvrir dans Google Maps",
  "store_description": "Informations supplémentaires sur le magasin.",
  "get_directions": "Itinéraire",
  "call_store": "Appeler le magasin",
  "share_location": "Partager l'emplacement",
  "browse_products": "Parcourir les produits",
  "connect_social": "Connectez-vous avec nous sur les réseaux sociaux",
  "no_social": "Aucun lien social disponible",
  "ready_to_visit": "Prêt à nous rendre visite ?",
  "visit_us_text": "Venez découvrir nos produits en personne. Nous sommes ravis de vous servir !",
  "get_directions_cta": "Itinéraire",
  "call_us_now": "Appelez-nous maintenant",
  "default_description": "Votre partenaire de confiance pour les produits technologiques premium et un service exceptionnel.",
  "default_address": "Douala, Cameroun",
  "default_phone": " ",
  "default_email": "info@sucesstechnology.com",
  "default_hours": "Lun - Ven: 7h00 - 20h00\nDim: Fermé",
  "our_store": "Notre magasin",
  "visit_our_store": "Visitez notre magasin",
  "find_us_at": "Trouvez-nous à",
  "location_copied": "Lien de localisation copié !",
  "locate_us": "Nous trouver",
        "checkout_page_title": "Paiement · Sucess Technology",
  "checkout_title": "Paiement",
  "back_to_cart": "Retour au panier",
  "order_placed_title": "Commande passée ! 🎉",
  "order_placed_sub": "Merci pour votre commande. Nous la confirmerons sous peu.",
  "confirmation_sent": "Une confirmation a été envoyée à votre adresse e-mail.",
  "continue_shopping": "Continuer les achats",
  "view_orders": "Voir les commandes",
  "contact_whatsapp": "Contacter le vendeur sur WhatsApp",
  "shipping_info": "Informations de livraison",
  "full_name": "Nom complet",
  "full_name_placeholder": "Jean Dupont",
  "name_error": "Veuillez entrer votre nom complet",
  "email_address": "Adresse e-mail",
  "email_placeholder": "vous@exemple.com",
  "email_error": "Veuillez entrer un e-mail valide",
  "phone_number": "Numéro de téléphone",
  "phone_placeholder": "+237 6XX XXX XXX",
  "phone_error": "Veuillez entrer votre numéro de téléphone",
  "phone_help": "Nous l'utiliserons pour vous contacter concernant votre commande",
  "delivery_address": "Adresse de livraison",
  "address_placeholder": "123 Rue Principale, Ville, Pays",
  "address_error": "Veuillez entrer votre adresse de livraison",
  "payment_method": "Méthode de paiement",
  "payment_help": "Pour votre sécurité, veuillez attendre la confirmation de votre commande avant d'effectuer tout paiement. Nous vous contacterons.",
  "select_payment": "Sélectionnez une méthode de paiement",
  "payment_mobile_money": "Mobile Money (MTN, Orange, Moov)",
  "payment_cash": "Paiement à la livraison",
  "payment_credit_card": "Carte de crédit (Stripe)",
  "payment_paypal": "PayPal",
  "payment_bank": "Virement bancaire",
  "payment_error": "Veuillez sélectionner une méthode de paiement",
  "terms_agree": "J'accepte les conditions d'utilisation et la politique de confidentialité.",
  "terms_error": "Vous devez accepter les conditions pour passer une commande",
  "order_notes": "Notes de commande (Optionnel)",
  "notes_placeholder": "Instructions spéciales pour la livraison...",
  "place_order": "Passer la commande",
  "order_summary": "Récapitulatif de la commande",
  "loading_cart": "Chargement du panier...",
  "subtotal": "Sous-total",
  "delivery_fee": "Frais de livraison",
  "total": "Total",
  "free": "Gratuit",
  "cart_empty": "Votre panier est vide",
  "browse_products": "Parcourir les produits",
  "qty": "Qté",
  "cart_empty_error": "Votre panier est vide",
  "please_login": "Veuillez vous connecter pour passer une commande",
  "placing_order": "Passage de la commande...",
  "order_failed": "Échec de la commande. Veuillez réessayer.",
  "order_placed_success": "Commande passée avec succès ! 🎉",
  "order": "Commande",
  "placed": "Passée",
  "thank_you": "Merci",
  "your_order": "Votre commande",
  "totaling": "totalisant",
  "has_been_received": "a été reçue.",
  "customer": "Client",
  "email": "E-mail",
  "phone": "Téléphone",
  "address": "Adresse",
  "payment": "Paiement",
  "notes": "Notes",
  "items": "Articles",
         "category_page_title": "Catégorie · Sucess Technology",
  "all_categories": "Toutes les catégories",
  "explore_collection": "Explorez notre collection",
  "explore_collection_full": "Explorez notre collection complète",
  "discover_products": "Découvrez nos produits {0}",
  "load_more": "Charger plus",
  "no_products_found": "Aucun produit trouvé pour cette catégorie.",
  "you_may_also_like": "🔄 Vous aimerez aussi",
  "loading_more_products": "Chargement de plus de produits...",
  "footer_products": "Produits",
  "footer_phone": "Téléphone",
  "footer_tablet": "Tablette",
  "footer_audio": "Audio",
  "footer_follow": "📱 Suivez-nous",
  "footer_about": "À propos",
  "about_us": "À propos de nous",
  "press": "Presse",
  "locate_us": "📍 Nous trouver",
  "footer_contact": "📞 Contact",
  "copyright": "© 2024 Sucess Technology. Tous droits réservés.",
  "badge_hot": "TENDANCE",
  "badge_new": "NOUVEAU",
  "badge_deal": "OFFRE",
  "add_to_cart": "Ajouter au panier",
  "cart_empty": "Panier vide",
  "product_not_found": "Produit non trouvé",
  "added_to_cart": "ajouté au panier !",
  "cart_cleared": "Panier vidé",
  "error_loading_products": "Erreur de chargement des produits",
  "category_phone": "Téléphone",
  "category_tablet": "Tablette",
  "category_audio": "Audio",
  "category_laptop": "Ordinateur portable",
  "category_accessories": "Accessoires",
  "category_watch": "Montre",
  "category_camera": "Appareil photo",
  "category_gaming": "Jeux",
  "category_tv": "TV",
  "category_headphones": "Casques",
  "category_speaker": "Enceinte",
  "category_charger": "Chargeur",
  "category_case": "Étui",
  "category_screen": "Écran",
  "category_uncategorized": "Non catégorisé",
        "cart_page_title": "Votre panier - Success Technology",
  "your_cart": "Votre panier",
  "items_count": "{0} articles",
  "items_count_zero": "0 articles",
  "continue_shopping": "Continuer les achats",
  "loading_cart": "Chargement de votre panier...",
  "order_summary": "Récapitulatif de la commande",
  "subtotal": "Sous-total",
  "shipping": "Livraison",
  "discount": "Réduction",
  "total": "Total",
  "discount_code_placeholder": "Code de réduction",
  "apply": "Appliquer",
  "proceed_to_checkout": "Procéder au paiement",
  "you_may_also_like": "Vous aimerez aussi ajouter ces articles à votre sac",
  "footer_products": "Produits",
  "footer_phone": "Téléphone",
  "footer_tablet": "Tablette",
  "footer_audio": "Audio",
  "footer_follow": "📱 Suivez-nous",
  "footer_about": "À propos",
  "locate_us": "📍 Nous trouver",
  "footer_contact": "📞 Contact",
  "cart_empty_title": "Votre panier est vide",
  "cart_empty_sub": "Il semble que vous n'ayez pas encore ajouté d'articles à votre panier.",
  "start_shopping": "Commencer les achats",
  "items": "article",
  "deal": "OFFRE",
  "decrease_quantity": "Diminuer la quantité",
  "increase_quantity": "Augmenter la quantité",
  "remove_item": "Supprimer l'article",
  "remove": "Supprimer",
  "removed_from_cart": "Retiré",
  "from_cart": "du panier",
  "free": "Gratuit",
  "discount_applied": "Réduction de 10% appliquée !",
  "discount_applied_20": "Réduction de 20% appliquée !",
  "discount_removed": "Réduction supprimée",
  "invalid_discount": "Code de réduction invalide",
  "please_login_to_checkout": "Veuillez vous connecter pour passer à la caisse",
        "brand_page_title": "marque · Sucess Technology",
  "all_brands": "Toutes les marques",
  "explore_collection": "Explorez notre collection",
  "load_more": "Charger plus",
  "no_products_found": "Aucun produit trouvé pour cette marque.",
  "you_may_also_like": "🔄 Vous aimerez aussi",
  "loading_more_products": "Chargement de plus de produits...",
  "footer_products": "Produits",
  "footer_phone": "Téléphone",
  "footer_tablet": "Tablette",
  "footer_audio": "Audio",
  "footer_follow": "📱 Suivez-nous",
  "footer_about": "À propos",
  "about_us": "À propos de nous",
  "press": "Presse",
  "locate_us": "📍 Nous trouver",
  "footer_contact": "📞 Contact",
  "copyright": "© 2024 Sucess Technology. Tous droits réservés.",
  "badge_hot": "TENDANCE",
  "badge_new": "NOUVEAU",
  "badge_deal": "OFFRE",
  "add_to_cart": "Ajouter au panier",
  "cart_empty": "Panier vide",
        "account_page_title": "Paramètres du compte · Success Technology",
  "account_settings_title": "Paramètres du compte",
  "signed_in_guest": "Connecté en tant qu'invité",
  "guest": "Invité",
  "not_logged_in": "Non connecté",
  "nav_profile": "Profil",
  "nav_orders": "Mes commandes",
  "nav_security": "Sécurité",
  "nav_preferences": "Préférences",
  "nav_logout": "Déconnexion",
  "quick_links": "Liens rapides",
  "about_us": "À propos de nous",
  "terms": "Conditions générales",
  "locate_us": "Nous trouver",
  "profile_info": "Informations du profil",
  "enable_editing": "Activer l'édition",
  "full_name": "Nom complet",
  "full_name_placeholder": "Votre nom complet",
  "name_required": "Le nom est requis",
  "email_address": "Adresse e-mail",
  "email_placeholder": "vous@exemple.com",
  "email_cannot_change": "L'e-mail ne peut pas être modifié",
  "phone_number": "Numéro de téléphone",
  "phone_placeholder": "+1 234 567 890",
  "address": "Adresse",
  "address_placeholder": "123 Rue Principale, Ville",
  "bio": "Bio",
  "bio_placeholder": "Parlez-nous un peu de vous...",
  "save_changes": "Enregistrer les modifications",
  "reset": "Réinitialiser",
  "my_orders": "Mes commandes",
  "loading_orders": "Chargement de vos commandes...",
  "security": "Sécurité",
  "current_password": "Mot de passe actuel",
  "current_password_placeholder": "Entrez le mot de passe actuel",
  "current_password_required": "Le mot de passe actuel est requis",
  "new_password": "Nouveau mot de passe",
  "new_password_placeholder": "Entrez un nouveau mot de passe (min 6 caractères)",
  "password_min_length": "Le mot de passe doit comporter au moins 6 caractères",
  "confirm_password": "Confirmer le nouveau mot de passe",
  "confirm_password_placeholder": "Confirmer le nouveau mot de passe",
  "passwords_mismatch": "Les mots de passe ne correspondent pas",
  "update_password": "Mettre à jour le mot de passe",
  "danger_zone": "Zone dangereuse",
  "delete_account_warning": "Supprimer définitivement votre compte et toutes les données associées.",
  "delete_account": "Supprimer le compte",
  "preferences_title": "Préférences",
  "email_notifications": "Notifications par e-mail",
  "pref_order_updates": "Mises à jour et confirmations de commandes",
  "pref_promotions": "E-mails promotionnels et offres",
  "pref_newsletter": "Newsletter et mises à jour des produits",
  "privacy": "Confidentialité",
  "pref_profile_visibility": "Afficher les informations du profil aux autres utilisateurs",
  "pref_order_history": "Afficher l'historique des commandes",
  "save_preferences": "Enregistrer les préférences",
  "delete_account_modal_title": "Supprimer le compte",
  "delete_account_modal_text": "Êtes-vous sûr de vouloir supprimer votre compte ? Cette action est permanente et ne peut pas être annulée. Toutes vos données, y compris les commandes et les préférences, seront perdues.",
  "cancel": "Annuler",
  "delete_account_confirm": "Supprimer le compte",
  "no_orders_yet": "Aucune commande pour l'instant",
  "start_shopping": "Commencez à magasiner pour voir vos commandes ici.",
  "browse_products": "Parcourir les produits",
  "order_number": "Commande",
  "items": "articles",
  "please_login": "Veuillez vous connecter",
  "login_to_view_orders": "Connectez-vous pour voir vos commandes.",
  "failed_to_load": "Échec du chargement des commandes",
  "try_again_later": "Veuillez réessayer plus tard.",
  "retry": "Réessayer",
        "about_page_title": "À propos de nous · Sucess Technology",
  "loading_info": "Chargement des informations de l'entreprise...",
  "about_title": "À propos de",
  "hero_description": "Votre partenaire de confiance pour les produits technologiques premium et un service exceptionnel. Nous nous engageons à vous offrir le meilleur de l'innovation technologique.",
  "location_default": "Douala, Cameroun",
  "hours_default": "Lun - Ven: 7h00 - 20h00",
  "stat_years": "3+",
  "stat_years_label": "Années d'excellence",
  "stat_products": "500+",
  "stat_products_label": "Produits disponibles",
  "stat_customers": "1000+",
  "stat_customers_label": "Clients satisfaits",
  "shop_photo": "Photo du magasin",
  "mission_title": "Notre Mission",
  "mission_text": "Fournir des produits technologiques de haute qualité et un service client exceptionnel qui permet aux individus et aux entreprises d'accomplir davantage.",
  "vision_title": "Notre Vision",
  "vision_text": "Devenir le partenaire technologique le plus fiable en Afrique, connectant les gens avec des solutions innovantes qui améliorent leur vie.",
  "values_title": "Nos Valeurs",
  "values_text": "L'intégrité, l'innovation et la centration sur le client guident tout ce que nous faisons. Nous croyons en l'établissement de relations durables avec notre communauté.",
  "who_we_are": "Qui nous sommes",
  "about_description": "Sucess Technology est un détaillant technologique de premier plan dédié à offrir les produits les plus récents et les plus innovants à nos clients. Avec une passion pour la technologie et un engagement envers l'excellence, nous organisons une sélection diversifiée d'appareils et d'accessoires de haute qualité.",
  "about_description_2": "Notre équipe de passionnés de technologie est là pour vous aider à trouver le produit parfait pour vos besoins. Que vous soyez un professionnel à la recherche du dernier ordinateur portable, un étudiant cherchant une tablette fiable, ou un passionné de technologie explorant de nouveaux gadgets, nous avons ce qu'il vous faut.",
  "about_description_3": "Nous croyons que la technologie devrait être accessible à tous, c'est pourquoi nous offrons des prix compétitifs, des options de paiement flexibles et un support client exceptionnel. Votre satisfaction est notre priorité.",
  "get_in_touch": "Contactez-nous",
  "shop_now": "Acheter maintenant",
  "core_values": "Nos Valeurs Fondamentales",
  "value_trust": "Confiance & Intégrité",
  "value_innovation": "Innovation",
  "value_customer": "Client d'abord",
  "value_quality": "Excellence de la qualité",
  "value_community": "Focus sur la communauté",
  "value_africa": "Innovation africaine",
  "get_in_touch_title": "Contactez-nous",
  "connect_social": "Connectez-vous avec nous sur les réseaux sociaux",
  "no_contact": "Aucune information de contact disponible",
  "no_social": "Aucun lien social disponible",
        "wishlist_page_title": "Votre liste de souhaits - Sucess Technology",
  "wishlist_title": "Votre liste de souhaits",
  "items_count": "{0} articles",
  "clear_all": "Tout effacer",
  "browse_products": "Parcourir les produits",
  "badge_deal": "🔥 Offre",
  "badge_new": "✨ Nouveau",
  "badge_hot": "⚡ Tendance",
  "remove": "Retirer de la liste",
  "view_details": "Voir les détails",
  "empty_wishlist_title": "Votre liste de souhaits est vide",
  "empty_wishlist_sub": "Enregistrez vos articles préférés et revenez-les consulter à tout moment.",
  "start_exploring": "Commencer à explorer",
  "error_title": "Une erreur s'est produite",
  "error_sub": "Impossible de charger votre liste de souhaits. Veuillez réessayer plus tard.",
  "retry": "Réessayer",
         "hot_products_title": "Produits Chauds",
  "view_all": "Voir Tout",
  "no_hot_products": "Aucun produit chaud disponible",
  "discount_percent": "-{0}%",
  "view_details": "Voir les détails",
        "no_products_found": "Aucun produit trouvé",
  "check_back_later": "Revenez plus tard pour les nouvelles arrivées",
  "badge_discount": "-{0}%",
  "badge_new": "✨ Nouveau",
  "badge_hot": "⚡ Tendance",
  "view_details": "Voir les détails",
  "loading_more": "Chargement de plus de produits...",
  "load_more": "Charger plus de produits",
  "no_products_available": "Aucun produit disponible",
  "error_loading": "Erreur de chargement des produits",
  "please_try_again": "Veuillez réessayer plus tard",
  "retry": "Réessayer",
        "no_featured_title": "Aucun produit en vedette disponible",
  "no_featured_sub": "Revenez bientôt pour nos dernières offres !",
  "badge_deal": "🔥 Offre",
  "badge_new": "✨ Nouveau",
  "badge_hot": "⚡ Tendance",
  "view_details": "Voir les détails",
        "searching": "Recherche en cours...",
  "no_results": "Aucun produit trouvé pour",
  "view_all_results": "Voir tous les résultats pour",
  "search_unavailable": "Recherche indisponible. Veuillez réessayer.",
  "type_to_search": "Tapez pour rechercher des produits...",
        "no_categories": "Aucune catégorie disponible",
  "no_brands": "Aucune marque disponible",
  "no_products": "Aucun produit disponible",
  "load_failed": "Échec du chargement des produits",
  "product_count": "{count} produits",
  "product_price": "FCFA{price}",
        "nav_products": "Produits",
  "nav_categories": "Catégories",
  "nav_brands": "Marques",
  "nav_contact": "Contact",
  "view_all": "Voir tout →",
  "loading": "Chargement...",
  "search_placeholder": "Rechercher...",
  "guest": "Invité",
  "my_orders": "Mes commandes",
  "settings": "Paramètres",
  "logout": "Déconnexion",
  "about_us": "À propos de nous",
  "terms": "Conditions générales",
  "locate_us": "Nous trouver",
  "login": "Se connecter",
  "register": "S'inscrire",
  "home": "Accueil",
  "for_you": "pour vous",
  "cart": "Panier",
  "wishlist": "Liste de souhaits",
  "notifications_title": "Notifications",
  "welcome_back": "Bon retour",
  "login_subtitle": "Connectez-vous à votre compte",
  "email_address": "Adresse e-mail",
  "email_placeholder": "vous@exemple.com",
  "email_error": "Veuillez entrer un e-mail valide",
  "password": "Mot de passe",
  "password_placeholder": "Entrez votre mot de passe",
  "password_error": "Le mot de passe est requis",
  "remember_me": "Se souvenir de moi",
  "no_account": "Vous n'avez pas de compte ?",
  "create_account": "Créer un compte",
  "join_subtitle": "Rejoignez Success Technology",
  "full_name": "Nom complet",
  "name_placeholder": "Jean Dupont",
  "name_error": "Le nom est requis",
  "password_help": "Le mot de passe doit comporter au moins 6 caractères",
  "phone_number": "Numéro de téléphone",
  "phone_placeholder": "6XX XXX XXX",
  "phone_help": "Nous l'utiliserons pour vous contacter concernant vos commandes",
  "phone_error": "Veuillez entrer un numéro de téléphone valide",
  "delivery_address": "Adresse de livraison",
  "address_placeholder": "123 Rue Principale, Ville, Pays",
  "address_help": "Votre adresse de livraison par défaut",
  "address_error": "Veuillez entrer votre adresse",
  "country_region": "Pays / Région",
  "select_country": "Sélectionnez votre pays",
  "country_help": "Sélectionnez votre pays pour la livraison et la devise",
  "country_error": "Veuillez sélectionner votre pays",
  "terms_agree": "J'accepte les conditions d'utilisation et la politique de confidentialité.",
  "terms_error": "Vous devez accepter les conditions pour créer un compte",
  "have_account": "Vous avez déjà un compte ?",
        "nav_products": "Produits",
  "nav_categories": "Catégories",
  "nav_brands": "Marques",
  "nav_contact": "Contact",
  "notif_empty_title": "Aucune notification",
  "notif_empty_sub": "Vous êtes à jour !",
  "notif_mark_all": "Tout marquer comme lu",
  "notif_unread_count": "{count} non lus",
  "notif_clear_all": "Effacer toutes les notifications",
  "notif_just_now": "À l'instant",
        "page_title": "bienvenue · Sucess Technology",
  "hero_badge": "🔥 Nouvelle Arrivée",
  "hero_title": "Smartphone nouvelle génération",
  "hero_brand": "Marque X",
  "hero_price": "999 €",
  "hero_original_price": "1 299 €",
  "hero_discount": "-23%",
  "hero_desc": "Vivez le futur dès aujourd'hui.",
  "hero_btn": "Acheter maintenant",
  "categories_tag": "Catégories populaires",
  "categories_title": "Acheter par catégorie",
  "categories_sub": "Explorez nos départements les plus vendus",
  "view_all": "Voir tout",
  "deals_title": "Offres du jour",
  "deals_view_all": "Voir Plus →",
  "related_title": "Vous aimerez aussi",
  "footer_products": "Produits",
  "footer_phone": "Téléphone",
  "footer_tablet": "Tablette",
  "footer_audio": "Audio",
  "footer_follow": "📱 Suivez-nous",
  "footer_about": "À propos",
  "footer_about_us": "À propos de nous",
  "footer_locate": "Nous trouver",
  "footer_terms": "Conditions générales",
  "footer_contact": "📞 Contact",
        "notif_redirect_checkout": " Redirection vers la caisse...",
        "notif_welcome_back": " Bon retour, {name}!",
        "notif_login_failed": "❌ Échec de la connexion. Veuillez réessayer.",
        "notif_registration_success": "Compte créé avec succès ! Bienvenue {name} !",
        "notif_registration_failed": "❌ Échec de l'inscription. Veuillez réessayer.",
        "notif_logout_success": "👋 Déconnexion réussie"
    }
};
